### PR TITLE
Don't prevent galaxies from spawning planets

### PR DESCRIPTION
**Pull request by juped**
I have both a pecuniary and a sentimental interest in these ships. If there are issues, I am available to assist in debugging of same.

Yours,
~rolsut-rospub, galactic orphan

### CODE REVIEW

**Comment by Fang-** [comment]
Removing this actually breaks a bunch of assumptions in other parts of the contracts, most prominently but not limited to the escape logic.

I'm afraid we made a very conscious decision to not support such planets for now, and at this point in time I wouldn't feel comfortable at all making changes like this.

I do sympathize with your case, especially if that means losing your personal identity. If it's any consolation, I'm pretty sure there's an arvo-side solution to be found to this. Not entirely sure, but that might be as simple as force-inserting the desired planet+keys into your galaxy's copy of the chain.

**Comment by joemfb** [comment]
We could support such planets by treating them the way we treat moons (captive, keys signed by prefix parent). This would complicate some logic in %ames and %jael, but probably not too much.

/cc @cgyarvin

**Comment by juped** [comment]
Burning large amounts of address space (a bit under 2^24 planets including, nontrivially to _me_ even if not to you, my personal identity), with no notice to anyone who doesn't continually audit the code (I follow development at a high level, but I have a very time-demanding job), hardly seems worth the corner-cutting on some sponsorship logic it may enable now - corner-cutting that will, of course, be a burden on future generations.

I shouldn't need to work on Urbit full-time to learn about these plans or attempt to head them off. On the other hand, recognizing the small and scrappy nature of the Urbit team, my services are available to help fix this situation - not just out of self-interest.

**Comment by cgyarvin** [comment]
I like Joe’s plan of pushing it into userspace, as it were.  We need to test this mode anyway — the idea of Urbit’s own consensus is only sleeping, not dead.

**Comment by juped** [comment]
I don't want weird crippled half-planets. If anything, these are premium limited-run planets.

I don't care that much for ethereum, but if there's an authoritative registry of title and you can't be on it, you're a crippled half-planet.

(Sorry, not getting email notifications on this thread for some reason)

**Comment by cgyarvin** [comment]
You’re probably right in principle but it won’t change the contracts.  Let some dust settle, then propose an amendment in the senate.

**Comment by juped** [comment]
While there may be social value to having an uncontroversial constitutional amendment "on deck" (assuming proper testing, I can't imagine any galaxy holder voting against "more planets for galaxy holders"), I haven't audited this whole contract system - so I don't know if any of the "assumptions" are baked into non-upgradeable subcontracts.

This situation is arbitrary and inexplicable. I'm glad I was able to catch it, but I shouldn't have had to catch it.

**Pull request closed without merging**
