### PR TITLE
Migration script now includes multiple ship classes and default invite pools

### PR DESCRIPTION
**Pull request by vvisigoth**
Migration script now includes multiple ship classes and default invite pools

### CODE REVIEW

**Comment by Fang-** [comment]
What prompted this? Pretty sure re-enabling "default" chain state (and pushing this onto the npm package) will break downstream tests that expect a clean Azimuth environment. (At the very least, azimuth-js.) I'm fine with providing a "set up test state" script, but we shouldn't add it into the standard deploy script.

**Comment by vvisigoth** [comment]
This is a useful migration script for developing on Bridge as is, thought
it might be useful for others. Up until now, it's been stored as a gist,
copied into node_modules/azimuth-solidity which is...inelegant.

Do you have any idea how we can make this accessible to brdige dev?
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment]
> Do you have any idea how we can make this accessible to bridge dev?

I don't have a better idea right now, but I'll make a task for investigating if there's something fancier we can do if you want. Sometime next week.

**Comment by vvisigoth** [comment]
Yeah, totally not urgent.
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment]
Closing as superseded by #22.

**Pull request closed without merging**
